### ISSUE TITLE
languages-map.json not created following installation steps in readme

### ISSUE THREAD

**Issue by mugwhump** [pajecawav/ghloc-web#26]
I needed to run `pnpm build-languages` for the file to be generated.

Also FYI, [ghloc.ifels.dev](https://ghloc.ifels.dev/) is down, so your website doesn't work. Anyone who wants to use this will need to run their own instance of ghloc in server mode.

**Comment by pajecawav** [comment]
Hi, sorry for late response. Thanks for reporting issues with development docs! I've updated dev/build scripts. [ghloc.ifels.dev](https://ghloc.ifels.dev) had some issues with SSL certificates which were resolved the same day.
