### ISSUE TITLE
Failed to load LOC stats: Too large repository

### ISSUE THREAD

**Issue by lechuhuuha** [pajecawav/ghloc-web#77]
Open this repo caused error
Failed to load LOC stats: Too large repository
https://github.com/hpcaitech/Open-Sora

![image](https://github.com/pajecawav/ghloc-web/assets/59781669/c8e8f82f-5e56-4805-99a6-8f71bf722489)

**Comment by pajecawav** [comment]
Hi, sorry for late response. To count lines of code we have to download the repo as a ZIP archive first. Looks like this repo has a lot of images so it exceeds or max ZIP archive limit
