### ISSUE TITLE
Add avg/mean and median

### ISSUE THREAD

**Issue by Peacexoom** [pajecawav/ghloc-web#78]
Add two more columns to see avg/mean and median for lines of code of files in each folder

![Screenshot 2024-07-11 113139](https://github.com/pajecawav/ghloc-web/assets/104450933/bd989efa-fe92-43a1-8eec-4739ebd01ceb)

**Comment by pajecawav** [comment]
Sorry, just now noticed your issue. I'm not sure what's the point of adding avg/mean/median for LoC's. Initial goal of this project was to quickly explore random repos that I see on GitHub , not to perform some kind of statistical analysis on them

**Comment by Peacexoom** [comment]
You are right. Adding this seems unnecessary.

**Comment by Peacexoom** [comment]
By the way, awesome project!

I was trying to find some good repository to make open source contribution but ended up picking too large repos. I was thinking to build something to get an estimate of size of the repo(LoC) and came across your project.

Really wonderful project.
